2022-05-30 17:40:23,891 - TeleBot - ERROR - A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty
2022-05-30 17:49:23,575 - TeleBot - ERROR - A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty
2022-05-30 18:33:05,162 - TeleBot - ERROR - A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2022-05-31 15:32:25,602 - TeleBot - ERROR - A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Unsupported start tag "p" at byte offset 0
2022-05-31 23:30:42,690 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
2022-05-31 23:30:42,694 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\gerku\PycharmProjects\Telegram bot\.venv\lib\site-packages\telebot\__init__.py", line 649, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\gerku\PycharmProjects\Telegram bot\.venv\lib\site-packages\telebot\util.py", line 107, in raise_exceptions
    raise self.exception_info
  File "C:\Users\gerku\PycharmProjects\Telegram bot\.venv\lib\site-packages\telebot\util.py", line 89, in run
    task(*args, **kwargs)
  File "C:\Users\gerku\PycharmProjects\Telegram bot\.venv\lib\site-packages\telebot\__init__.py", line 359, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\gerku\PycharmProjects\Telegram bot\.venv\lib\site-packages\telebot\__init__.py", line 337, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\gerku\PycharmProjects\Telegram bot\.venv\lib\site-packages\telebot\apihelper.py", line 322, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\gerku\PycharmProjects\Telegram bot\.venv\lib\site-packages\telebot\apihelper.py", line 152, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\gerku\PycharmProjects\Telegram bot\.venv\lib\site-packages\telebot\apihelper.py", line 179, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized

